services:
  storage1:
    build: .
    container_name: storage1
    ports:
      - "4001:3000"
    volumes:
      - storage1_data:/app/images

  storage2:
    build: .
    container_name: storage2
    ports:
      - "4002:3000"
    volumes:
      - storage2_data:/app/images

  storage3:
    build: .
    container_name: storage3
    ports:
      - "4003:3000"
    volumes:
      - storage3_data:/app/images
  storage4:
    build: .
    container_name: storage4
    ports:
      - "4004:3000"
    volumes:
      - storage4_data:/app/images

volumes:
  storage1_data:
  storage2_data:
  storage3_data:
  storage4_data:
