services:
  manage-image:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: manage-image
    ports:
      - "8001:3000"
    environment:
      - NODE_ENV=development
      - MYSQL_WRITE_URI=${MYSQL_WRITE_URI}
      - MYSQL_READ_URI=${MYSQL_READ_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - TIME_MICROSERVICE_HOST=time-microservice:50051
    volumes:
      - .:/app
      - /app/node_modules
      - ./../time-microservice/protos:/app/time-microservice/protos
    restart: unless-stopped
    networks:
      - gallery-network

networks:
  gallery-network:
    external: true
